package gui;

/**
 * Bezeichnungen der einzelnen Tiles im Tileset
 */
public enum Tile {
	// Tileset Row 1
	BACKGROUND, FIVEELEMENTONE_HORIZONTAL, FIVEELEMENTTWO_HORIZONTAL, FIVEELEMENTTHREE_HORIZONTAL, FIVEELEMENTFOUR_HORIZONTAL, FIVELEMENTFIVE_HORIZONTAL, FOURELEMENTONE_HORIZONTAL, FOURELEMENTTWO_HORIZONTAL, FOURELEMENTTHREE_HORIZONTAL, FOURELEMENTFOUR_HORIZONTAL, // Tileset Row 2
	THREEELEMENTONE_HORIZONTAL, THREEELEMENTTWO_HORIZONTAL, THREEELEMENTTHREE_HORIZONTAL, TWOELEMENTONE_HORIZONTAL, TWOELEMENTTWO_HORIZONTAL, MISS, HIT_WATER, GREY, HIT_TRANSPARENT, DEFINITELY_NO_SHIP, // Tileset Row 3
	FIVEELEMENTONE_VERTICAL, FOURELEMENTONE_VERTICAL, THREEELEMENTONE_VERTICAL, TWOELEMENTONE_VERTICAL, E2, E3, E4, E5, E6, E7, // Tileset Row 4
	FIVEELEMENTTWO_VERTICAL, FOURELEMENTTWO_VERTICAL, THREEELEMENTWO_VERTICAL, TWOELEMENTTWO_VERTICAL, E8, E9, E10, E11, E12, E13, // Tileset Row 5
	FIVEELEMENTTHREE_VERTICAL, FOURELEMENTTHREE_VERTICAL, THREEELEMENTHREE_VERTICAL, E14, E15, E16, E17, E18, E19, E20, // Tilset Row 6
	FIVEELEMENTFOUR_VERTICAL, FOURELEMENTFOUR_VERTICAL, E21, E22, E23, E24, E25, E26, E27, E28, // Tileset Row 7
	FIVEELEMENTFIVE_VERTICAL, E29, E30, E31, E32, E33, E34, E35, E36, E37, // Tileset Row 8
	N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, // Tileset Row 9
	N11, N12, N13, N14, N15, N16, N17, N18, N19, N20, // Tileset Row 10
	N21, N22, N23, N24, N25, N26, N27, N28, N29, N30
}